# Default values for angular-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: kkalynovskyi
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: angular-app
  type: ClusterIP
  exposeContainers:
    - name: angular
      externalPort: 80
      path: "/"
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - angular.local
  annotations:
    kubernetes.io/ingress.class: nginx
deployment:
  containers:
    angular:
      internalPort: 8080
resources: {}
