apiVersion: v1
kind: Service
metadata:
  name: {{ template "angular-app.fullname" . }}
  labels:
    app: {{ template "angular-app.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $container := .Values.service.exposeContainers }}
    {{- $containerName := $container.name -}}
    {{- $externalPort := $container.externalPort -}}
    {{- $containerSpec := index $.Values.deployment.containers $containerName }}
    - port: {{ $externalPort }}
      targetPort: {{ $containerSpec.internalPort }}
      protocol: TCP
      name: {{ $containerName }}
    {{- end }}
  selector:
    app: {{ template "angular-app.name" . }}
    release: {{ .Release.Name }}
